apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyverno-policies
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    path: manager/resources/kyverno-policies
    repoURL: https://github.com/weallfloatdownhere/gitopsHub.git
    targetRevision: HEAD
    directory:
      recurse: true
      include: '*.yaml'
  destination:
    namespace: kyverno
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=false
    - Replace=false