apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kyverno

resources:
  - namespace.yaml

helmCharts:
- name: kyverno
  namespace: kyverno
  releaseName: kyverno
  repo: https://kyverno.github.io/kyverno
  version: 3.0.5
  includeCRDs: true
  valuesFile: values.yaml