apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argo-rollouts

bases:
- ../base/install.yaml
- ../base/namespace.yaml

resources:
- dashboard.yaml
- notifications.yaml

patches:
- path: sync-wave.yaml
  target:
     group: '.*'
     kind: CustomResourceDefinition