# https://github.com/kubernetes-sigs/cluster-api/tree/main/bootstrap/kubeadm

apiVersion: operator.cluster.x-k8s.io/v1alpha2
kind: ControlPlaneProvider
metadata:
  name: kubeadm
  namespace: capi-operator-system
spec:
  version: v1.5.1