apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argo-rollouts

resources:
- namespace.yaml

helmCharts:
- name: argo-rollouts
  namespace: argo-rollouts
  releaseName: argo-rollouts
  repo: https://argoproj.github.io/argo-helm
  version: 2.32.0
  includeCRDs: true
  valuesFile: values.yaml