image:
  repository: quay.io/mittwald/kubernetes-replicator
  pullPolicy: Always

grantClusterAdmin: true
automountServiceAccountToken: true

livenessProbe:
  initialDelaySeconds: 60
  periodSeconds: 10
  timeoutSeconds: 1
  failureThreshold: 3
  successThreshold: 1

readinessProbe:
  initialDelaySeconds: 60
  periodSeconds: 10
  timeoutSeconds: 1
  failureThreshold: 3
  successThreshold: 1

args: []
updateStrategy: {}

serviceAccount:
  create: true
  annotations: {}
  name:
  privileges: []
  automountServiceAccountToken: true

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
podSecurityContext: {}
securityContext: {}
priorityClassName: ""
resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
podLabels: {}
podAnnotations: {}