---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: root
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://github.com/weallfloatdownhere/gitopsHub.git
      revision: HEAD
      directories:
        - path: 'administration/resources/**/overlays/current/'
  template:
    metadata:
      name: '{{path[2]}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/weallfloatdownhere/gitopsHub.git
        targetRevision: HEAD
        path: '{{`{{path}}`}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path[3]}}'
      ignoreDifferences:
      - group: "apps"
        kind: "Deployment"
        jsonPointers:
        - /spec/replicas
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
          allowEmpty: true
        syncOptions:
        - CreateNamespace=true
        - RespectIgnoreDifferences=true