---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: root
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://github.com/weallfloatdownhere/gitopsHub.git
      revision: HEAD
      directories:
        - path: administration/resources/*
        - path: administration/resources/**/base
          exclude: true
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/weallfloatdownhere/gitopsHub.git
        targetRevision: HEAD
        path: '{{path}}/overlays/current'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}'
      ignoreDifferences:
        - group: "apps"
          kind: "Deployment"
          jsonPointers:
            - /spec/replicas
        - group: kyverno.io
          kind: ClusterPolicy
          jqPathExpressions:
            - .spec.rules[] | select(.name|test("autogen-."))
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
          allowEmpty: true
        syncOptions:
        - CreateNamespace=true
        - Replace=true
        - RespectIgnoreDifferences=true
