apiVersion: v1
kind: Secret
metadata:
  name: argocd-secret
  namespace: argocd
type: Opaque
data:
  # default: admin:password
  admin.password: JDJhJDEwJEhRM1l2aGNZNnFLRDU5dmovRE1YamUuM212ZWQzaG1ESXIwcDY2bDg5bEtXNnlRU3BnSW1P