# https://taskfile.dev

version: '3'

silent: true

vars:
  GIT_ROOT:
    sh: echo "$(git rev-parse --show-toplevel)"
  GIT_ORIGIN:
    sh: echo "$(git ls-remote --get-url origin)"
  STATIC_DIR_ARGO: '{{.GIT_ROOT}}/management/argo'
  STATIC_FILE_BOOTSTRAP: '{{.GIT_ROOT}}/management/bootstrap/core/bootstrap.yaml'
  STATIC_FILE_CLUSTER_CONF: '{{.GIT_ROOT}}/management/bootstrap/configuration.yaml'

tasks:
  default:
    desc: Show this message.
    cmds:
      - task --list-all

  mkcorefile:
    silent: true
    desc: "Generate a Corefile | task mkcorefile KUBECONFIG=path/to/my/core.bootstrap"
    cmds:
      - |
        RND="{{.USER_WORKING_DIR}}/$(cat /dev/urandom | tr -dc 'a-z0-9' | fold -w 6 | head -n 1).core.bootstrap"
        echo SOURCE_REPO={{.GIT_ORIGIN}} > $RND
        echo SOURCE_KUBECONFIG=$(cat {{.KUBECONFIG}} | base64 -w0) >> $RND
        echo "New corefile at: $RND"
        cat $RND
    preconditions:
      - sh: test -f '{{.KUBECONFIG}}'
        msg: "ERROR - Specified KUBECONFIG does NOT exists.."
    requires:
      vars: [KUBECONFIG, GIT_ROOT, GIT_ORIGIN]