# https://taskfile.dev

version: '3'

# vars:
#   GREETING: "Hello world"

vars:
  GIT_DIR: { sh: git rev-parse --show-toplevel }
  ARGO_DIR: "{{.GIT_DIR}}/administration/resources/argocd/overlays/current"
  ARGO_BOOTSTRAP_APP: "{{.GIT_DIR}}/administration/bootstrap/app-bootstrap.yaml"

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true

  deploy:hub:
    deps: [tool:kubectl]
    desc: Deploy administration resources to a fresh k8s cluster (MASTER/HUB).
    cmds:
      - kubectl apply -k {{.ARGO_DIR}}
      - kubectl wait --for=condition=available deployment -l "app.kubernetes.io/name=argocd-server" -n argocd --timeout=300s
    preconditions:
      - sh: test ! -z $KUBECONFIG
        msg: "ERROR - Please set the KUBECONFIG environment variable.."
      - sh: test -f $KUBECONFIG
        msg: "ERROR - Specified KUBECONFIG not found.."
      - sh: test -d {{.ARGO_DIR}}
        msg: "ERROR - ArgoCD administration directory not found.."
      - sh: test -f {{.GIT_DIR}}/.tmp/tools/kubectl
        msg: "ERROR - Kubectl cli not found.."

  deploy:spoke:
    deps: [tool:kubectl]
    desc: Setup and bootstrap the current dir spoke.
    dir: '{{.USER_WORKING_DIR}}'
    cmds:
      - |
        export KUBECONFIG="$PWD/kubeconfig"
        cat <<EOF | kubectl apply --kubeconfig kubeconfig -n kube-system  -f -
        apiVersion: v1
        kind: Secret
        metadata:
          name: argocd-manager-token
          namespace: kube-system 
          annotations:
            kubernetes.io/service-account.name: argocd-manager
        type: kubernetes.io/service-account-token
        EOF

        TOKEN=$(kubectl get -n kube-system secret/argocd-manager-token -o jsonpath='{.data.token}' | base64 --decode)
        echo $TOKEN

    preconditions:
      - sh: test -f $PWD/kubeconfig
        msg: "ERROR - No kubeconfig file found in the current directory.."


  tool:kubectl:
    desc: Temporarily download kubectl client.
    silent: true
    internal: true
    cmds:
      - mkdir -p {{.GIT_DIR}}/.tmp/tools
      - curl -L -o {{.GIT_DIR}}/.tmp/tools/kubectl "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
      - chmod +x {{.GIT_DIR}}/.tmp/tools/kubectl
    status:
      - test -f {{.GIT_DIR}}/.tmp/tools/kubectl