# https://taskfile.dev

version: '3'

vars:
  STATIC_DIR_ARGO: '{{.GIT_ROOT}}/management/argo'
  STATIC_FILE_BOOTSTRAP: '{{.GIT_ROOT}}/management/bootstrap/core/bootstrap.yaml'
  STATIC_FILE_CLUSTER_CONF: '{{.GIT_ROOT}}/management/bootstrap/configuration.yaml'

includes:
  corefile:
    taskfile: management/taskfiles/corefile.yml
    vars:
      KUBECONFIG: '{{.KUBECONFIG}}'

tasks:
  default:
    cmds:
      - echo "K8s bootstraping master repository."

  #corefile:read:
  #  aliases:
  #    - read
  #  silent: true
  #  dotenv: ['{{.GIT_ROOT}}/sample.core.bootstrap','{{.COREFILE}}']
  #  cmds:
  #    - echo "{{.COREFILE}}"
  #    - echo $SOURCE_REPO
  #    #- echo "{{.GIT_ROOT}}"
  #    #- echo "{{.STATIC_DIR_ARGO}}"
  #    #- echo "{{.STATIC_FILE_BOOTSTRAP}}"
  #    #- echo "{{.STATIC_FILE_CLUSTER_CONF}}"
  #  preconditions:
  #    - sh: test -f '{{.COREFILE}}'
  #      msg: "Specified COREFILE not found: {{.COREFILE}}"
  #  requires:
  #    vars: [COREFILE]

    
