# https://taskfile.dev

version: "3"

includes:
  extras: hack/taskfiles/extras.yml
  master: hack/taskfiles/master.yml
  slaves: hack/taskfiles/slaves.yml

tasks:
  default:
    cmds:
      - echo "YEE"
