apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-api-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  project: default
  source:
    path: manager/resources/cluster-api-operator/overlay
    repoURL: https://github.com/weallfloatdownhere/gitopsHub.git
    targetRevision: HEAD
  destination:
    namespace: capi-operator-system
    server: https://kubernetes.default.svc

  ignoreDifferences:
  - group: "*"
    kind: "CustomResourceDefinition"
    jsonPointers:
    - /spec/conversion/webhook/clientConfig/caBundle

  syncPolicy:
    syncOptions:
    - RespectIgnoreDifferences=true
    - CreateNamespace=true
    automated:
      selfHeal: false
      prune: false