apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-api-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  project: default
  source:
    path: manager/resources/cluster-api-operator/overlay
    repoURL: https://github.com/weallfloatdownhere/gitopsHub.git
    targetRevision: HEAD
  destination:
    namespace: capi-operator-system
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: false
      prune: false