apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-api-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    path: manager/resources/cluster-api
    repoURL: https://github.com/weallfloatdownhere/gitopsHub.git
    targetRevision: HEAD
  destination:
    namespace: cluster-api-operator
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - RespectIgnoreDifferences=true
  ignoreDifferences:
    - group: '*'
      kind: CustomResourceDefinition
      jsonPointers:
      - /spec/conversion/webhook/clientConfig/caBundle