apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-api
  namespace: argocd
spec:
  project: default
  source:
    path: manager/resources/cluster-api
    repoURL: https://github.com/weallfloatdownhere/gitopsHub.git
    targetRevision: HEAD
    directory:
      recurse: true
      include: '{**/*.yaml}'
  destination:
    namespace: capi-operator-system
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=false
      - RespectIgnoreDifferences=true
      - SkipDryRunOnMissingResource=true
      - CreateNamespace=true