apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    path: manager/apps
    repoURL: https://github.com/weallfloatdownhere/gitopsHub.git
    targetRevision: HEAD
    directory:
      recurse: true
      exclude: 'root.yaml'
      include: '*.yaml'
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - RespectIgnoreDifferences=true