apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../applications/argocd
patches:
  - path: cm.argocd-cm.yaml
  - path: sec.admin-password.yaml
  - path: cm.argocd-cmd-params-cm.yaml
