# https://taskfile.dev

version: '3'

vars:
  GIT_ROOT:
    sh: echo "$(git rev-parse --show-toplevel)"
  GIT_REMOTE_URL:
    sh: echo $(cd {{.GIT_ROOT}} && git ls-remote --get-url origin)
  GIT_TYPE:
    sh: |
        if [ $(echo "{{.GIT_REMOTE_URL}}" | grep -c 'github.com') -gt 0 ]; then
            echo "GITHUB"
        elif [ $(echo "{{.GIT_REMOTE_URL}}" | grep -c 'bitbucket.org') -gt 0 ]; then
            echo "BITBUCKET"
        elif [ $(echo "{{.GIT_REMOTE_URL}}" | grep -c 'gitlab') -gt 0 ]; then
            echo "GITLAB"
        fi

dotenv: ['params.env', '.params.env', '{{.USER_WORKING_DIR}}/params.env', '{{.USER_WORKING_DIR}}/.params.env', '{{.GIT_ROOT}}/params.env']

tasks:
  default:
    silent: true
    cmds:
      - echo 'git repo       - {{.GIT_ROOT}}'
      - echo 'git remote url - {{.GIT_REMOTE_URL}}'
      - echo 'git type       - {{.GIT_TYPE}}'