apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml

helmGlobals: 
  chartHome: "../charts"

helmCharts:
- name: cert-manager
  releaseName: cert-manager
  version: v1.13.1
  namespace: cert-manager
  valuesFile: values.yaml

patches:
  - target:
       group: '.*'
       kind: CustomResourceDefinition
    path: crds-finilizers.yaml