apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# namespace: flux-system

resources:
  - ./namespace.yaml

helmGlobals: 
  chartHome: "../charts"

helmCharts:
- name: tf-controller
  releaseName: tf-controller
  version: 0.15.1
  namespace: flux-system
  includeCRDs: true
  valuesFile: values.yaml

patches:
  - target:
       group: '.*'
       kind: CustomResourceDefinition
    path: crds-sync-wave.yaml