# -- If `true`, install CRDs as part of the helm installation
installCRDs: true
clusterDomain: cluster.local

awsPackage:
  install: false
  tag: v4.38.0-v1alpha11
  repository: ghcr.io/tf-controller/aws-primitive-modules

metrics:
  enabled: false
  serviceMonitor:
    enabled: false
    namespace: ''
    labels: {}
    annotations: {}
    matchLabels: {}
    targetLabels: []
    endpoint:
      interval: "15s"
      scrapeTimeout: ""
      metricRelabelings: []
      relabelings: []

# -- Branch Based Planner-specific configurations
branchBasedPlanner:
  enabled: false
  image:
    repository: ghcr.io/weaveworks/branch-based-planner
    pullPolicy: IfNotPresent
    tag: ""
