apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-api
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  #finalizers:
  #  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    path: management/resources/cluster-api/overlays/current
    repoURL: https://github.com/weallfloatdownhere/gitopsHub.git
    targetRevision: HEAD
  destination:
    namespace: capi-operator-system
    server: https://kubernetes.default.svc
  ignoreDifferences:
    - group: '*'
      kind: CustomResourceDefinition
      jsonPointers:
      - /spec/conversion/webhook/clientConfig/caBundle
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - Validate=false
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - RespectIgnoreDifferences=true