# https://taskfile.dev

version: '3'

vars:
  GIT_ROOT:
    sh: echo "$(git rev-parse --show-toplevel)"

env:
  KUBECONFIG: '{{.GIT_ROOT}}/manager/manager.kubeconfig'

tasks:
  start:
    cmds:
      - minikube delete --all
      - rm -rf ~/.kube/config $KUBECONFIG
      - minikube start -p manager --memory 3078 --cpus 2 --network bridge
      - kubectl config view --context manager --flatten --minify > {{.GIT_ROOT}}/manager/k.tmp
      - mv {{.GIT_ROOT}}/manager/k.tmp $KUBECONFIG

  stop:
    cmds:
      - minikube delete --all
      - rm -rf ~/.kube/config 
      - rm -rf $KUBECONFIG