---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: crossplane
  repo: https://charts.crossplane.io/master/
  version: 1.2.1
  releaseName: crossplane
  # valuesFile: values.yaml