REQUIRED_PLUGINS = %w(vagrant-libvirt)
exit unless REQUIRED_PLUGINS.all? do |plugin|
  Vagrant.has_plugin?(plugin) || (
    puts "The #{plugin} plugin is required. Please install it with:"
    puts "$ vagrant plugin install #{plugin}"
    false
  )
end

Vagrant.configure("2") do |config|
    config.vagrant.plugins = "vagrant-libvirt"
    config.vm.define :cluster do |cluster|
      cluster.vm.box = "generic/ubuntu2004"
      cluster.vm.network :private_network, :ip => "192.168.121.164"
      cluster.vm.provider :libvirt do |libvirt|
        libvirt.qemu_use_session = false
        # if the above doesn't work, try uncommenting the following instead
        #libvirt.uri = 'qemu:///system'
      end
    end
end