---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
- name: cert-manager
  repo: https://charts.jetstack.io
  version: 1.13.0
  releaseName: cert-manager
  namespace: cert-manager
  valuesInline:
    installCRDs: true
    startupapicheck:
      enabled: false