apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: capi-operator-system

resources:
  - ../base/install.yaml
  - ../base/namespace.yaml

patches:
 - target:
      group: '.*'
      kind: CustomResourceDefinition
   path: crds-finilizers.yaml