apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# namespace: cert-manager

helmCharts:
- name: cert-manager
  namespace: cert-manager
  releaseName: cert-manager
  repo: https://charts.jetstack.io
  version: v1.13.1
  includeCRDs: true
  valuesFile: values.yaml

resources:
- namespace.yaml

commonAnnotations:
  argocd.argoproj.io/sync-wave: "-10"

