installCRDs: true
featureGates: ""
namespace: "cert-manager"
enableCertificateOwnerRef: false

prometheus:
  enabled: false
  servicemonitor:
    enabled: false
    prometheusInstance: default
    targetPort: 9402
    path: /metrics
    interval: 60s
    scrapeTimeout: 30s

webhook:
  replicaCount: 1
  timeoutSeconds: 20

startupapicheck:
  enabled: false