kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "cert-manager-istio-csr.name" . }}-leases
  namespace: {{ .Values.app.controller.leaderElectionNamespace }}
  labels:
{{ include "cert-manager-istio-csr.labels" . | indent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "cert-manager-istio-csr.name" . }}-leases
subjects:
- kind: ServiceAccount
  name: {{ include "cert-manager-istio-csr.name" . }}
  namespace: {{ .Release.Namespace }}
