apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cluster-api

patches:
- target:
    kind: CoreProvider
    name: cluster-api
  patch: |-
    - op: replace
      path: /spec/version
      value: v1.4.3

resources:
- ./providers.ctrlplanes.yaml
- ./providers.infratructure.yaml
- ./providers.bootstrap.yaml
- ../base/cluster-api.yaml
- ./namespace.yaml