apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cluster-api

resources:
  - namespace.yaml

bases:
- ../base

patches:
  - target:
      kind: CoreProvider
      name: cluster-api
    path: version-core.cluster-api.yaml

  - target:
      kind: BootstrapProvider
      name: kubeadm
    path: version-bootstrap.kubeadm.yaml

  - target:
      kind: ControlPlaneProvider
      name: kubeadm
    path: version-infrastructure.byoh.yaml

  - target:
      kind: InfrastructureProvider
      name: docker
    path: version-infrastructure.docker.yaml

  - target:
      kind: InfrastructureProvider
      name: byoh
    path: version-infrastructure.byoh.yaml




  #  patch: |-
  #    - op: replace
  #      path: /spec/version
  #      value: v1.5.1
  #- target:
  #    kind: BootstrapProvider
  #    name: kubeadm
  #  patch: |-
  #    - op: replace
  #      path: /spec/version
  #      value: v1.5.1


#patches:
# - target:
#      group: operator.cluster.x-k8s.io
#      version: v1alpha2
#   path: namespaces.yaml