apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cluster-api

resources:
  - ../base/control-planes/kubeadm.yaml
  - ../base/bootstrap/kubeadm.yaml
  - ../base/infrastructure/byoh.yaml
  - ../base/infrastructure/docker.yaml
  - ../base/core/cluster-api.yaml
  - ../base/namespace.yaml

patches:
 - target:
      group: operator.cluster.x-k8s.io
      version: v1alpha2
   path: namespaces.yaml