apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cluster-api

resources:
  - ./providers.ctrlplanes.yaml
  - ./providers.infratructure.yaml
  - ./providers.bootstrap.yaml
  - ../base/cluster-api.yaml
  - ./namespace.yaml

patches:
  - target:
      kind: CoreProvider
      name: cluster-api
    path: version-cluster-api.yaml