apiVersion: builtin
kind: HelmChartInflationGenerator
name: cert-manager
metadata:
  name: cert-manager
namespace: cert-manager
repo: https://charts.jetstack.io
releaseName: cert-manager
IncludeCRDs: false
version: 1.13.1
valuesFile: values.yaml
