# https://taskfile.dev

version: '3'

vars:
  GIT_ROOT:
    sh: echo "$(git rev-parse --show-toplevel)"

tasks:
  start:
    aliases: [ load, reload ]
    desc: Load/reload development environement to a default factory settings kubernetes cluster.
    silent: true
    env:
      KUBECONFIG: '{{.GIT_ROOT}}/manager/manager.kubeconfig'
    cmds:
      - task: install
      - rm -rf ~/.kube/config $KUBECONFIG
      - minikube delete --all
      - minikube start -p manager --memory 3078 --cpus 2 --network bridge
      - kubectl config view --context manager --flatten --minify > {{.GIT_ROOT}}/manager/k.tmp
      - mv {{.GIT_ROOT}}/manager/k.tmp $KUBECONFIG

  install:
    internal: true
    silent: true
    desc: Install development environement pre-requirements.
    cmds:
      - sudo apt -y update
      - sudo apt -y install docker.io virtualbox
      - curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
      - sudo install minikube-linux-amd64 /usr/local/bin/minikube
    status:
      - test $(command -v minikube)

