apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../bases

patches:
- path: ./patch.argocd-cmd-params-cm.yaml
- path: ./patch.argocd-cm.yaml
- path: ./patch.admin-password.yaml