apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - https://raw.githubusercontent.com/argoproj/argo-cd/v2.8.4/manifests/install.yaml
  - namespace.yaml

patches:
  - path: cm.argocd-cm.yaml
  - path: sec.admin-password.yaml
  - path: cm.argocd-cmd-params-cm.yaml
