apiVersion: operator.cluster.x-k8s.io/v1alpha2
kind: CoreProvider
metadata:
  name: cluster-api
spec:
  version: v1.4.3
  manager:
    featureGates:
      MachinePool: true
      ClusterResourceSet: true
      ClusterClass: true