apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml

helmGlobals: 
  chartHome: "../charts"

helmCharts:
- name: kyverno
  releaseName: kyverno
  version: 3.0.5
  namespace: kyverno
  valuesFile: values.yaml