apiVersion: v1
kind: Namespace
metadata:
  name: capi-operator-system
  labels:
    clusterctl.cluster.x-k8s.io/core: capi-operator
    control-plane: controller-manager
    argocd.argoproj.io/managed-by: argocd