apiVersion: v1
kind: Service
metadata:
  name: ingress-nginx-controller
  namespace: ingress-nginx
spec:
  ports:
  - appProtocol: http
    name: http
    port: 80
    protocol: TCP
    nodePort: 30010
  - appProtocol: https
    name: https
    port: 443
    protocol: TCP
    nodePort: 30443
  type: NodePort