apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
- ../base/install.yaml
- ../base/namespace.yaml

patchesStrategicMerge:
  - argocd-cmd-params-cm.yaml
  - argocd-cm.yaml
  - admin-password.yaml

components:
- https://github.com/argoproj-labs/argocd-extensions/manifests