apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../base/install.yaml
- ../base/namespace.yaml

patches:
- path: argocd-cmd-params-cm.yaml
- path: argocd-cm.yaml
- path: admin-password.yaml

components:
- https://github.com/argoproj-labs/argocd-extensions/manifests