# https://github.com/kubernetes-sigs/cluster-api-operator/tree/main/docs#installing-the-coreprovider

apiVersion: operator.cluster.x-k8s.io/v1alpha2
kind: CoreProvider
metadata:
  name: cluster-api
spec:
  version: v1.4.3