apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  #finalizers:
  #  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    path: management/applications
    repoURL: https://github.com/weallfloatdownhere/gitopsHub.git
    targetRevision: HEAD
    directory:
      recurse: true
      exclude: 'root.yaml'
      include: '{*/*.yaml}'
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Replace=true
      - CreateNamespace=true
      - RespectIgnoreDifferences=true