---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
- name: kyverno
  repo: https://kyverno.github.io/kyverno/
  version: 3.0.5
  releaseName: kyverno
  valuesFile: ../../overlay/values.yaml