{{ if .Values.awsPackage.install }}
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: aws-package
  annotations:
    metadata.weave.works/description: "This is the AWS package containing primitive modules for Weave TF-controller."
    metadata.weave.works/docs-url: "https://github.com/tf-controller/aws-primitive-modules"
spec:
  interval: 1h0m0s
  ref:
    tag: {{ .Values.awsPackage.tag }}
  url: oci://{{ .Values.awsPackage.repository }}
{{ end }}
