apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-api-providers
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    path: management/resources/cluster-api/providers
    repoURL: https://github.com/weallfloatdownhere/gitopsHub.git
    targetRevision: HEAD
    directory:
      recurse: true
      include: '{**/*.yaml}'
  destination:
    namespace: capi-system
    server: https://kubernetes.default.svc
  ignoreDifferences:
    - group: '*'
      kind: CustomResourceDefinition
      jsonPointers:
      - /spec/conversion/webhook/clientConfig/caBundle
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true