apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    path: infrastructure/manager/.root
    repoURL: $SOURCE_REPO
    targetRevision: HEAD
    helm:
      releaseName: root
      ignoreMissingValueFiles: true
      parameters:
        - name: "sourceUrl"
          value: $SOURCE_REPO
      valueFiles:
        - ../services/enabled.yaml
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      allowEmpty: false
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - RespectIgnoreDifferences=true