apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    path: management/resources/cert-manager/overlays/current
    repoURL: https://github.com/weallfloatdownhere/gitopsHub.git
    targetRevision: HEAD
  destination:
    namespace: cert-manager
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
      # - Replace=true
  #ignoreDifferences:
  #  - group: admissionregistration.k8s.io
  #    kind: ValidatingWebhookConfiguration
  #    name: cert-manager-webhook
  #    jqPathExpressions:
  #      - .webhooks[].namespaceSelector.matchExpressions[] | select(.key == "control-plane")