apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyverno
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    path: management/resources/kyverno/overlays/current
    repoURL: https://github.com/weallfloatdownhere/gitopsHub.git
    targetRevision: HEAD
  destination:
    namespace: kyverno
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyverno-policies
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    path: management/resources/kyverno/addons/policies
    repoURL: https://github.com/weallfloatdownhere/gitopsHub.git
    targetRevision: HEAD
    directory:
      recurse: true
      include: '*.yaml'
  destination:
    namespace: kyverno
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - Replace=true