apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: node-problem-detector
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    path: manager/resources/node-problem-detector/overlay
    repoURL: https://github.com/weallfloatdownhere/gitopsHub.git
    targetRevision: HEAD
  destination:
    namespace: node-problem-detector
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: false
      prune: false
    syncOptions:
    - CreateNamespace=true
