apiVersion: builtin
kind: HelmChartInflationGenerator
metadata:
  name: kyverno
name: kyverno
namespace: kyverno
repo: https://kyverno.github.io/kyverno
version: 3.0.5
releaseName: kyverno
IncludeCRDs: true
valuesFile: values.yaml